%% Phase Velocity
f50_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(1),...
                          D5_D8.narrowband_phase_velocity(1),...
                          D6_D11.narrowband_phase_velocity(1)];
f100_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(2),...
                          D5_D8.narrowband_phase_velocity(2),...
                          D6_D11.narrowband_phase_velocity(2)];
f150_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(3),...
                          D5_D8.narrowband_phase_velocity(3),...
                          D6_D11.narrowband_phase_velocity(3)];
f200_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(4),...
                          D5_D8.narrowband_phase_velocity(4),...
                          D6_D11.narrowband_phase_velocity(4)];
f250_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(5),...
                          D5_D8.narrowband_phase_velocity(5),...
                          D6_D11.narrowband_phase_velocity(5)];
f300_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(6),...
                          D5_D8.narrowband_phase_velocity(6),...
                          D6_D11.narrowband_phase_velocity(6)];
f350_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(7),...
                          D5_D8.narrowband_phase_velocity(7),...
                          D6_D11.narrowband_phase_velocity(7)];
f400_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(8),...
                          D5_D8.narrowband_phase_velocity(8),...
                          D6_D11.narrowband_phase_velocity(8)];
f450_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(9),...
                          D5_D8.narrowband_phase_velocity(9),...
                          D6_D11.narrowband_phase_velocity(9)];
f500_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(10),...
                          D5_D8.narrowband_phase_velocity(10),...
                          D6_D11.narrowband_phase_velocity(10)];
f550_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(11),...
                          D5_D8.narrowband_phase_velocity(11),...
                          D6_D11.narrowband_phase_velocity(11)];
f600_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(12),...
                          D5_D8.narrowband_phase_velocity(12),...
                          D6_D11.narrowband_phase_velocity(12)];
f650_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(13),...
                          D5_D8.narrowband_phase_velocity(13),...
                          D6_D11.narrowband_phase_velocity(13)];
f700_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity(14),...
                          D5_D8.narrowband_phase_velocity(14),...
                          D6_D11.narrowband_phase_velocity(14)];

upper_f50_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(1),...
                          D5_D8.narrowband_phase_velocity_upper_limit(1),...
                          D6_D11.narrowband_phase_velocity_upper_limit(1)];
upper_f100_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(2),...
                          D5_D8.narrowband_phase_velocity_upper_limit(2),...
                          D6_D11.narrowband_phase_velocity_upper_limit(2)];
upper_f150_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(3),...
                          D5_D8.narrowband_phase_velocity_upper_limit(3),...
                          D6_D11.narrowband_phase_velocity_upper_limit(3)];
upper_f200_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(4),...
                          D5_D8.narrowband_phase_velocity_upper_limit(4),...
                          D6_D11.narrowband_phase_velocity_upper_limit(4)];
upper_f250_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(5),...
                          D5_D8.narrowband_phase_velocity_upper_limit(5),...
                          D6_D11.narrowband_phase_velocity_upper_limit(5)];
upper_f300_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(6),...
                          D5_D8.narrowband_phase_velocity_upper_limit(6),...
                          D6_D11.narrowband_phase_velocity_upper_limit(6)];
upper_f350_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(7),...
                          D5_D8.narrowband_phase_velocity_upper_limit(7),...
                          D6_D11.narrowband_phase_velocity_upper_limit(7)];
upper_f400_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(8),...
                          D5_D8.narrowband_phase_velocity_upper_limit(8),...
                          D6_D11.narrowband_phase_velocity_upper_limit(8)];
upper_f450_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(9),...
                          D5_D8.narrowband_phase_velocity_upper_limit(9),...
                          D6_D11.narrowband_phase_velocity_upper_limit(9)];
upper_f500_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(10),...
                          D5_D8.narrowband_phase_velocity_upper_limit(10),...
                          D6_D11.narrowband_phase_velocity_upper_limit(10)];
upper_f550_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(11),...
                          D5_D8.narrowband_phase_velocity_upper_limit(11),...
                          D6_D11.narrowband_phase_velocity_upper_limit(11)];
upper_f600_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(12),...
                          D5_D8.narrowband_phase_velocity_upper_limit(12),...
                          D6_D11.narrowband_phase_velocity_upper_limit(12)];
upper_f650_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(13),...
                          D5_D8.narrowband_phase_velocity_upper_limit(13),...
                          D6_D11.narrowband_phase_velocity_upper_limit(13)];
upper_f700_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_upper_limit(14),...
                          D5_D8.narrowband_phase_velocity_upper_limit(14),...
                          D6_D11.narrowband_phase_velocity_upper_limit(14)];
                      
lower_f50_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(1),...
                          D5_D8.narrowband_phase_velocity_lower_limit(1),...
                          D6_D11.narrowband_phase_velocity_lower_limit(1)];
lower_f100_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(2),...
                          D5_D8.narrowband_phase_velocity_lower_limit(2),...
                          D6_D11.narrowband_phase_velocity_lower_limit(2)];
lower_f150_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(3),...
                          D5_D8.narrowband_phase_velocity_lower_limit(3),...
                          D6_D11.narrowband_phase_velocity_lower_limit(3)];
lower_f200_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(4),...
                          D5_D8.narrowband_phase_velocity_lower_limit(4),...
                          D6_D11.narrowband_phase_velocity_lower_limit(4)];
lower_f250_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(5),...
                          D5_D8.narrowband_phase_velocity_lower_limit(5),...
                          D6_D11.narrowband_phase_velocity_lower_limit(5)];
lower_f300_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(6),...
                          D5_D8.narrowband_phase_velocity_lower_limit(6),...
                          D6_D11.narrowband_phase_velocity_lower_limit(6)];
lower_f350_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(7),...
                          D5_D8.narrowband_phase_velocity_lower_limit(7),...
                          D6_D11.narrowband_phase_velocity_lower_limit(7)];
lower_f400_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(8),...
                          D5_D8.narrowband_phase_velocity_lower_limit(8),...
                          D6_D11.narrowband_phase_velocity_lower_limit(8)];
lower_f450_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(9),...
                          D5_D8.narrowband_phase_velocity_lower_limit(9),...
                          D6_D11.narrowband_phase_velocity_lower_limit(9)];
lower_f500_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(10),...
                          D5_D8.narrowband_phase_velocity_lower_limit(10),...
                          D6_D11.narrowband_phase_velocity_lower_limit(10)];
lower_f550_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(11),...
                          D5_D8.narrowband_phase_velocity_lower_limit(11),...
                          D6_D11.narrowband_phase_velocity_lower_limit(11)];
lower_f600_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(12),...
                          D5_D8.narrowband_phase_velocity_lower_limit(12),...
                          D6_D11.narrowband_phase_velocity_lower_limit(12)];
lower_f650_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(13),...
                          D5_D8.narrowband_phase_velocity_lower_limit(13),...
                          D6_D11.narrowband_phase_velocity_lower_limit(13)];
lower_f700_kHz_phase_velocity=[D2_D5.narrowband_phase_velocity_lower_limit(14),...
                          D5_D8.narrowband_phase_velocity_lower_limit(14),...
                          D6_D11.narrowband_phase_velocity_lower_limit(14)];
                      
                      
height=[100,200,300];

errorbar(height,(f400_kHz_phase_velocity./c).*100,(lower_f400_kHz_phase_velocity./c).*100,(upper_f400_kHz_phase_velocity./c).*100); hold all;
errorbar(height,(f350_kHz_phase_velocity./c).*100,(lower_f350_kHz_phase_velocity./c).*100,(upper_f350_kHz_phase_velocity./c).*100);
errorbar(height,(f300_kHz_phase_velocity./c).*100,(lower_f300_kHz_phase_velocity./c).*100,(upper_f300_kHz_phase_velocity./c).*100);
errorbar(height,(f250_kHz_phase_velocity./c).*100,(lower_f250_kHz_phase_velocity./c).*100,(upper_f250_kHz_phase_velocity./c).*100);
errorbar(height,(f200_kHz_phase_velocity./c).*100,(lower_f200_kHz_phase_velocity./c).*100,(upper_f200_kHz_phase_velocity./c).*100);
errorbar(height,(f150_kHz_phase_velocity./c).*100,(lower_f150_kHz_phase_velocity./c).*100,(upper_f150_kHz_phase_velocity./c).*100);
errorbar(height,(f100_kHz_phase_velocity./c).*100,(lower_f100_kHz_phase_velocity./c).*100,(upper_f100_kHz_phase_velocity./c).*100);
errorbar(height,(f50_kHz_phase_velocity./c).*100,(lower_f50_kHz_phase_velocity./c).*100,(upper_f50_kHz_phase_velocity./c).*100);
xlabel('Channel height (meters)');
ylabel('Phase velocity (% of c)');
legend('400 kHz','350 kHz','300 kHz','250 kHz',...
    '200 kHz','150 kHz','100 kHz','50 kHz','location','northwest');
grid;

%% Group Velocity
f50_kHz_group_velocity=[D2_D5.narrowband_group_velocity(1),...
                          D5_D8.narrowband_group_velocity(1),...
                          D8_D11.narrowband_group_velocity(1)];
f100_kHz_group_velocity=[D2_D5.narrowband_group_velocity(2),...
                          D5_D8.narrowband_group_velocity(2),...
                          D8_D11.narrowband_group_velocity(2)];
f150_kHz_group_velocity=[D2_D5.narrowband_group_velocity(3),...
                          D5_D8.narrowband_group_velocity(3),...
                          D8_D11.narrowband_group_velocity(3)];
f200_kHz_group_velocity=[D2_D5.narrowband_group_velocity(4),...
                          D5_D8.narrowband_group_velocity(4),...
                          D8_D11.narrowband_group_velocity(4)];
f250_kHz_group_velocity=[D2_D5.narrowband_group_velocity(5),...
                          D5_D8.narrowband_group_velocity(5),...
                          D8_D11.narrowband_group_velocity(5)];
f300_kHz_group_velocity=[D2_D5.narrowband_group_velocity(6),...
                          D5_D8.narrowband_group_velocity(6),...
                          D8_D11.narrowband_group_velocity(6)];
f350_kHz_group_velocity=[D2_D5.narrowband_group_velocity(7),...
                          D5_D8.narrowband_group_velocity(7),...
                          D8_D11.narrowband_group_velocity(7)];
f400_kHz_group_velocity=[D2_D5.narrowband_group_velocity(8),...
                          D5_D8.narrowband_group_velocity(8),...
                          D8_D11.narrowband_group_velocity(8)];

upper_f50_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(1),...
                          D5_D8.narrowband_group_velocity_upper_limit(1),...
                          D8_D11.narrowband_group_velocity_upper_limit(1)];
upper_f100_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(2),...
                          D5_D8.narrowband_group_velocity_upper_limit(2),...
                          D8_D11.narrowband_group_velocity_upper_limit(2)];
upper_f150_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(3),...
                          D5_D8.narrowband_group_velocity_upper_limit(3),...
                          D8_D11.narrowband_group_velocity_upper_limit(3)];
upper_f200_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(4),...
                          D5_D8.narrowband_group_velocity_upper_limit(4),...
                          D8_D11.narrowband_group_velocity_upper_limit(4)];
upper_f250_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(5),...
                          D5_D8.narrowband_group_velocity_upper_limit(5),...
                          D8_D11.narrowband_group_velocity_upper_limit(5)];
upper_f300_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(6),...
                          D5_D8.narrowband_group_velocity_upper_limit(6),...
                          D8_D11.narrowband_group_velocity_upper_limit(6)];
upper_f350_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(7),...
                          D5_D8.narrowband_group_velocity_upper_limit(7),...
                          D8_D11.narrowband_group_velocity_upper_limit(7)];
upper_f400_kHz_group_velocity=[D2_D5.narrowband_group_velocity_upper_limit(8),...
                          D5_D8.narrowband_group_velocity_upper_limit(8),...
                          D8_D11.narrowband_group_velocity_upper_limit(8)];
                      
lower_f50_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(1),...
                          D5_D8.narrowband_group_velocity_lower_limit(1),...
                          D8_D11.narrowband_group_velocity_lower_limit(1)];
lower_f100_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(2),...
                          D5_D8.narrowband_group_velocity_lower_limit(2),...
                          D8_D11.narrowband_group_velocity_lower_limit(2)];
lower_f150_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(3),...
                          D5_D8.narrowband_group_velocity_lower_limit(3),...
                          D8_D11.narrowband_group_velocity_lower_limit(3)];
lower_f200_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(4),...
                          D5_D8.narrowband_group_velocity_lower_limit(4),...
                          D8_D11.narrowband_group_velocity_lower_limit(4)];
lower_f250_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(5),...
                          D5_D8.narrowband_group_velocity_lower_limit(5),...
                          D8_D11.narrowband_group_velocity_lower_limit(5)];
lower_f300_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(6),...
                          D5_D8.narrowband_group_velocity_lower_limit(6),...
                          D8_D11.narrowband_group_velocity_lower_limit(6)];
lower_f350_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(7),...
                          D5_D8.narrowband_group_velocity_lower_limit(7),...
                          D8_D11.narrowband_group_velocity_lower_limit(7)];
lower_f400_kHz_group_velocity=[D2_D5.narrowband_group_velocity_lower_limit(8),...
                          D5_D8.narrowband_group_velocity_lower_limit(8),...
                          D8_D11.narrowband_group_velocity_lower_limit(8)];
                      
                      
height=[100,200,300];

figure;
% errorbar(height,(f400_kHz_group_velocity./c).*100,(lower_f400_kHz_group_velocity./c).*100,(upper_f400_kHz_group_velocity./c).*100); hold all;
% errorbar(height,(f350_kHz_group_velocity./c).*100,(lower_f350_kHz_group_velocity./c).*100,(upper_f350_kHz_group_velocity./c).*100); hold all;
errorbar(height,(f300_kHz_group_velocity./c).*100,(lower_f300_kHz_group_velocity./c).*100,(upper_f300_kHz_group_velocity./c).*100); hold all;
errorbar(height,(f250_kHz_group_velocity./c).*100,(lower_f250_kHz_group_velocity./c).*100,(upper_f250_kHz_group_velocity./c).*100);
errorbar(height,(f200_kHz_group_velocity./c).*100,(lower_f200_kHz_group_velocity./c).*100,(upper_f200_kHz_group_velocity./c).*100);
errorbar(height,(f150_kHz_group_velocity./c).*100,(lower_f150_kHz_group_velocity./c).*100,(upper_f150_kHz_group_velocity./c).*100);
errorbar(height,(f100_kHz_group_velocity./c).*100,(lower_f100_kHz_group_velocity./c).*100,(upper_f100_kHz_group_velocity./c).*100);
errorbar(height,(f50_kHz_group_velocity./c).*100,(lower_f50_kHz_group_velocity./c).*100,(upper_f50_kHz_group_velocity./c).*100);
xlabel('Channel height (meters)');
ylabel('Group velocity (% of c)');
legend('300 kHz','250 kHz',...
    '200 kHz','150 kHz','100 kHz','50 kHz','location','northwest');
grid;
