%% Phase Velocity
f50_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(1),...
                          D3_D6.narrowband_phase_velocity(1),...
                          D6_D11.narrowband_phase_velocity(1)];
f100_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(2),...
                          D3_D6.narrowband_phase_velocity(2),...
                          D6_D11.narrowband_phase_velocity(2)];
f150_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(3),...
                          D3_D6.narrowband_phase_velocity(3),...
                          D6_D11.narrowband_phase_velocity(3)];
f200_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(4),...
                          D3_D6.narrowband_phase_velocity(4),...
                          D6_D11.narrowband_phase_velocity(4)];
f250_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(5),...
                          D3_D6.narrowband_phase_velocity(5),...
                          D6_D11.narrowband_phase_velocity(5)];
f300_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(6),...
                          D3_D6.narrowband_phase_velocity(6),...
                          D6_D11.narrowband_phase_velocity(6)];
f350_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(7),...
                          D3_D6.narrowband_phase_velocity(7),...
                          D6_D11.narrowband_phase_velocity(7)];
f400_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity(8),...
                          D3_D6.narrowband_phase_velocity(8),...
                          D6_D11.narrowband_phase_velocity(8)];

upper_f50_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(1),...
                          D3_D6.narrowband_phase_velocity_upper_limit(1),...
                          D6_D11.narrowband_phase_velocity_upper_limit(1)];
upper_f100_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(2),...
                          D3_D6.narrowband_phase_velocity_upper_limit(2),...
                          D6_D11.narrowband_phase_velocity_upper_limit(2)];
upper_f150_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(3),...
                          D3_D6.narrowband_phase_velocity_upper_limit(3),...
                          D6_D11.narrowband_phase_velocity_upper_limit(3)];
upper_f200_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(4),...
                          D3_D6.narrowband_phase_velocity_upper_limit(4),...
                          D6_D11.narrowband_phase_velocity_upper_limit(4)];
upper_f250_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(5),...
                          D3_D6.narrowband_phase_velocity_upper_limit(5),...
                          D6_D11.narrowband_phase_velocity_upper_limit(5)];
upper_f300_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(6),...
                          D3_D6.narrowband_phase_velocity_upper_limit(6),...
                          D6_D11.narrowband_phase_velocity_upper_limit(6)];
upper_f350_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(7),...
                          D3_D6.narrowband_phase_velocity_upper_limit(7),...
                          D6_D11.narrowband_phase_velocity_upper_limit(7)];
upper_f400_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_upper_limit(8),...
                          D3_D6.narrowband_phase_velocity_upper_limit(8),...
                          D6_D11.narrowband_phase_velocity_upper_limit(8)];
                      
lower_f50_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(1),...
                          D3_D6.narrowband_phase_velocity_lower_limit(1),...
                          D6_D11.narrowband_phase_velocity_lower_limit(1)];
lower_f100_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(2),...
                          D3_D6.narrowband_phase_velocity_lower_limit(2),...
                          D6_D11.narrowband_phase_velocity_lower_limit(2)];
lower_f150_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(3),...
                          D3_D6.narrowband_phase_velocity_lower_limit(3),...
                          D6_D11.narrowband_phase_velocity_lower_limit(3)];
lower_f200_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(4),...
                          D3_D6.narrowband_phase_velocity_lower_limit(4),...
                          D6_D11.narrowband_phase_velocity_lower_limit(4)];
lower_f250_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(5),...
                          D3_D6.narrowband_phase_velocity_lower_limit(5),...
                          D6_D11.narrowband_phase_velocity_lower_limit(5)];
lower_f300_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(6),...
                          D3_D6.narrowband_phase_velocity_lower_limit(6),...
                          D6_D11.narrowband_phase_velocity_lower_limit(6)];
lower_f350_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(7),...
                          D3_D6.narrowband_phase_velocity_lower_limit(7),...
                          D6_D11.narrowband_phase_velocity_lower_limit(7)];
lower_f400_kHz_phase_velocity=[D1_D3.narrowband_phase_velocity_lower_limit(8),...
                          D3_D6.narrowband_phase_velocity_lower_limit(8),...
                          D6_D11.narrowband_phase_velocity_lower_limit(8)];
                      
                      
height=[16,42.5,115];

errorbar(height,(f400_kHz_phase_velocity./c).*100,(lower_f400_kHz_phase_velocity./c).*100,(upper_f400_kHz_phase_velocity./c).*100); hold all;
errorbar(height,(f350_kHz_phase_velocity./c).*100,(lower_f350_kHz_phase_velocity./c).*100,(upper_f350_kHz_phase_velocity./c).*100);
errorbar(height,(f300_kHz_phase_velocity./c).*100,(lower_f300_kHz_phase_velocity./c).*100,(upper_f300_kHz_phase_velocity./c).*100);
errorbar(height,(f250_kHz_phase_velocity./c).*100,(lower_f250_kHz_phase_velocity./c).*100,(upper_f250_kHz_phase_velocity./c).*100);
errorbar(height,(f200_kHz_phase_velocity./c).*100,(lower_f200_kHz_phase_velocity./c).*100,(upper_f200_kHz_phase_velocity./c).*100);
errorbar(height,(f150_kHz_phase_velocity./c).*100,(lower_f150_kHz_phase_velocity./c).*100,(upper_f150_kHz_phase_velocity./c).*100);
errorbar(height,(f100_kHz_phase_velocity./c).*100,(lower_f100_kHz_phase_velocity./c).*100,(upper_f100_kHz_phase_velocity./c).*100);
errorbar(height,(f50_kHz_phase_velocity./c).*100,(lower_f50_kHz_phase_velocity./c).*100,(upper_f50_kHz_phase_velocity./c).*100);
xlabel('Channel height (meters)');
ylabel('Phase velocity (% of c)');
legend('400 kHz','350 kHz','300 kHz','250 kHz',...
    '200 kHz','150 kHz','100 kHz','50 kHz','location','northwest');
grid;

%% Group Velocity
f50_kHz_group_velocity=[D1_D3.narrowband_group_velocity(1),...
                          D3_D6.narrowband_group_velocity(1),...
                          D6_D11.narrowband_group_velocity(1)];
f100_kHz_group_velocity=[D1_D3.narrowband_group_velocity(2),...
                          D3_D6.narrowband_group_velocity(2),...
                          D6_D11.narrowband_group_velocity(2)];
f150_kHz_group_velocity=[D1_D3.narrowband_group_velocity(3),...
                          D3_D6.narrowband_group_velocity(3),...
                          D6_D11.narrowband_group_velocity(3)];
f200_kHz_group_velocity=[D1_D3.narrowband_group_velocity(4),...
                          D3_D6.narrowband_group_velocity(4),...
                          D6_D11.narrowband_group_velocity(4)];
f250_kHz_group_velocity=[D1_D3.narrowband_group_velocity(5),...
                          D3_D6.narrowband_group_velocity(5),...
                          D6_D11.narrowband_group_velocity(5)];
f300_kHz_group_velocity=[D1_D3.narrowband_group_velocity(6),...
                          D3_D6.narrowband_group_velocity(6),...
                          D6_D11.narrowband_group_velocity(6)];
f350_kHz_group_velocity=[D1_D3.narrowband_group_velocity(7),...
                          D3_D6.narrowband_group_velocity(7),...
                          D6_D11.narrowband_group_velocity(7)];
f400_kHz_group_velocity=[D1_D3.narrowband_group_velocity(8),...
                          D3_D6.narrowband_group_velocity(8),...
                          D6_D11.narrowband_group_velocity(8)];

upper_f50_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(1),...
                          D3_D6.narrowband_group_velocity_upper_limit(1),...
                          D6_D11.narrowband_group_velocity_upper_limit(1)];
upper_f100_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(2),...
                          D3_D6.narrowband_group_velocity_upper_limit(2),...
                          D6_D11.narrowband_group_velocity_upper_limit(2)];
upper_f150_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(3),...
                          D3_D6.narrowband_group_velocity_upper_limit(3),...
                          D6_D11.narrowband_group_velocity_upper_limit(3)];
upper_f200_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(4),...
                          D3_D6.narrowband_group_velocity_upper_limit(4),...
                          D6_D11.narrowband_group_velocity_upper_limit(4)];
upper_f250_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(5),...
                          D3_D6.narrowband_group_velocity_upper_limit(5),...
                          D6_D11.narrowband_group_velocity_upper_limit(5)];
upper_f300_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(6),...
                          D3_D6.narrowband_group_velocity_upper_limit(6),...
                          D6_D11.narrowband_group_velocity_upper_limit(6)];
upper_f350_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(7),...
                          D3_D6.narrowband_group_velocity_upper_limit(7),...
                          D6_D11.narrowband_group_velocity_upper_limit(7)];
upper_f400_kHz_group_velocity=[D1_D3.narrowband_group_velocity_upper_limit(8),...
                          D3_D6.narrowband_group_velocity_upper_limit(8),...
                          D6_D11.narrowband_group_velocity_upper_limit(8)];
                      
lower_f50_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(1),...
                          D3_D6.narrowband_group_velocity_lower_limit(1),...
                          D6_D11.narrowband_group_velocity_lower_limit(1)];
lower_f100_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(2),...
                          D3_D6.narrowband_group_velocity_lower_limit(2),...
                          D6_D11.narrowband_group_velocity_lower_limit(2)];
lower_f150_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(3),...
                          D3_D6.narrowband_group_velocity_lower_limit(3),...
                          D6_D11.narrowband_group_velocity_lower_limit(3)];
lower_f200_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(4),...
                          D3_D6.narrowband_group_velocity_lower_limit(4),...
                          D6_D11.narrowband_group_velocity_lower_limit(4)];
lower_f250_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(5),...
                          D3_D6.narrowband_group_velocity_lower_limit(5),...
                          D6_D11.narrowband_group_velocity_lower_limit(5)];
lower_f300_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(6),...
                          D3_D6.narrowband_group_velocity_lower_limit(6),...
                          D6_D11.narrowband_group_velocity_lower_limit(6)];
lower_f350_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(7),...
                          D3_D6.narrowband_group_velocity_lower_limit(7),...
                          D6_D11.narrowband_group_velocity_lower_limit(7)];
lower_f400_kHz_group_velocity=[D1_D3.narrowband_group_velocity_lower_limit(8),...
                          D3_D6.narrowband_group_velocity_lower_limit(8),...
                          D6_D11.narrowband_group_velocity_lower_limit(8)];
                      
                      
figure;
errorbar(height,(f400_kHz_group_velocity./c).*100,(lower_f400_kHz_group_velocity./c).*100,(upper_f400_kHz_group_velocity./c).*100); hold all;
errorbar(height,(f350_kHz_group_velocity./c).*100,(lower_f350_kHz_group_velocity./c).*100,(upper_f350_kHz_group_velocity./c).*100); hold all;
errorbar(height,(f300_kHz_group_velocity./c).*100,(lower_f300_kHz_group_velocity./c).*100,(upper_f300_kHz_group_velocity./c).*100); hold all;
errorbar(height,(f250_kHz_group_velocity./c).*100,(lower_f250_kHz_group_velocity./c).*100,(upper_f250_kHz_group_velocity./c).*100);
errorbar(height,(f200_kHz_group_velocity./c).*100,(lower_f200_kHz_group_velocity./c).*100,(upper_f200_kHz_group_velocity./c).*100);
errorbar(height,(f150_kHz_group_velocity./c).*100,(lower_f150_kHz_group_velocity./c).*100,(upper_f150_kHz_group_velocity./c).*100);
errorbar(height,(f100_kHz_group_velocity./c).*100,(lower_f100_kHz_group_velocity./c).*100,(upper_f100_kHz_group_velocity./c).*100);
errorbar(height,(f50_kHz_group_velocity./c).*100,(lower_f50_kHz_group_velocity./c).*100,(upper_f50_kHz_group_velocity./c).*100);
xlabel('Channel height (meters)');
ylabel('Group velocity (% of c)');
legend('400 kHz','350 kHz','300 kHz','250 kHz',...
    '200 kHz','150 kHz','100 kHz','50 kHz','location','northwest');
grid;
